# Site settings
baseURL = "https://uqmars.com/"
languageCode = "en-us"
title = "UQ MARS"


[params]

    # Add generic site parameters here that can be used across partials
    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    name = "UQ MARS"
    full_name = "The University of Queeensland Mechatronics and Robotics Society"

    description = "UQ Mars (Mechatronics and Robotics Society) is a community that fosters robotics and mechatronics skills through competitions, workshops, and social events, welcoming anyone with a passion for these fields."

    custom_css = ["/css/main.css", "/css/website.css"]
    custom_js  = ["/js/navigation.js", "/js/button-box.js", "/js/favicon.js"]
    custom_ico = "/img/favicon/favicon.ico"
    custom_fonts = []
